### ISSUE TITLE
[Feature request] Update data at the bottom when new data is entered on instrument editor

### ISSUE THREAD

**Issue by nicco1690** [jpage8580/GTUltra#14]
When I update the instruments that I'm using in my songs, sometimes I get the AD, SR positions mixed up, and end up creating weird unintentional instruments, however I often use the display on the bottom to make sure that what I entered was what I wanted. 

The bar that I'm talking about is this one:
![bar](https://user-images.githubusercontent.com/78063037/161874784-f2e6a67c-57c6-4c4f-8ff1-a1a9c7472791.PNG)

The issue that comes from this is that when you update the instrument's parameters, the bar doesn't update to show the changes that are made, and only do you get to see the new changes when you cursor down and then cursor back up again.

My wish for this is that the bar's display gets updated when you stroke a key to edit the instrument, so as to avoid this and make creating instruments just that little bit easier.

Thanks

PS: I've been enjoying the tracker a lot since I started learning it, so I might end up submitting [this](https://www.youtube.com/watch?v=YezLSRafu1Q) (when it's actually finished of course, right now it's very far from finished) as a demo song if that's possible? Thanks

**Comment by jpage8580** [comment]
Hey
I've updated the code to instantly change that display now. Thanks for making me aware of that one.

re: song - As you've helped out, sure. :)
