### ISSUE TITLE
Pattern looping doesn't work if a channel is muted

### ISSUE THREAD

**Issue by acrouzet** [jpage8580/GTUltra#20]

**Comment by jpage8580** [comment]
Can't repro. Looping works OK for me when channel is muted.
Code for muting only disables certain sid writes. other than that, the code paths are the same. So will need a repro

**Comment by acrouzet** [comment]
yeah, I tried it again with a different module and it worked....hm

**Comment by acrouzet** [comment]
I'm unable to repro the issue even with the same module. It honestly might just me not noticing that I put a note change in the middle of a pattern or something. I'll let you know if it happens to me again.

**Comment by jpage8580** [comment]
Can’t repro. Closing for now.
