### ISSUE TITLE
[Request] Add a "File already exists. Replace?" dialog when saving over an existing .sng

### ISSUE THREAD

**Issue by acrouzet** [jpage8580/GTUltra#25]
Me and others have saved over projects with blanks when trying to load numerous times.

**Comment by jpage8580** [comment]
Is this due to accidentally pressing F11 instead of F10? I changed the
panel colour to try to reduce this happening (making it clearer that you
were in the save panel).

But, yes, I could add a “are you sure?” If you try to save over a different
file than the one you last loaded.

**Comment by jpage8580** [comment]
Hats a very good point! My father is actually red/green colour blind.
I’ll add another check,as said before.

I was also thinking of auto-saving to a temp file every, say, 30 seconds.
(Maybe keeping the last 10 saves). Could be useful if there’s any accidents
or crashes..

**Comment by jpage8580** [comment]
Done. Let me know if that's OK for you

**Comment by acrouzet** [comment]
That looks alright, thank you!
