### ISSUE TITLE
.sng instrument name issue

### ISSUE THREAD

**Issue by acrouzet** [jpage8580/GTUltra#30]
The instrument names all have the first letter of the name of the first instrument at the beginning of them, and deleting that letter deletes the names of all the instruments.

**Comment by jpage8580** [comment]
Will take a look.I wonder if this was the same in the original GT editor,
as I don’t think I’ve touched this code.

**Comment by acrouzet** [comment]
This only started happening with the latest update in the new branch

**Comment by jpage8580** [comment]
Fixes pushed to branch
