### ISSUE TITLE
Instrument Copy/Pasting doesn't work sometimes

### ISSUE THREAD

**Issue by acrouzet** [jpage8580/GTUltra#33]

**Comment by jpage8580** [comment]
Can't repro when copy/pasting whilst selecting instrument parameters (AD / SR ... 1stFrame Wave.)
Only time this could be seen as a problem is if trying to copy/paste when editing the instrument name.
Could this be what you're experiencing?

Either way - I've pushed another version to the new orderlist branch that allows for instrument cut/copy/paste if you're also editing the instrument name too.  This does mean that CTRL_ has to be used to perform this (previously SHIFT_ would also work. However, you'd need shift for entering uppercase letters whilst editing the instrument name).

**Comment by acrouzet** [comment]
I believe I tried selecting the instrument parameters and it still didn't work, but I can't be certain. Either way, thanks and I'll let you know if it happens again.
