### ISSUE TITLE
1st frame waves' in-tracker behavior doesn't match export (or GT2 behavior)

### ISSUE THREAD

**Issue by acrouzet** [jpage8580/GTUltra#37]
In GTUltra's exported files (and the original GT2's tracker playback), the 1st frame wave's pitch matches that of the last frame before the new note. In GTUltra's tracker playback, the 1st frame wave's pitch is that of the note being played. 

In addition to this being a compatibility issue between GT2 and GTU, mismatch between preview and export may cause issues in complex sound arrangements where the 1st frame wave of an instrument isn't 0/test bit.

**Comment by jpage8580** [comment]
Thanks for this.
Can you tell me if this was also the case for the original GT/GTStereo
editor? Will make it easier to track if it’s something that I’ve
introduced.

**Comment by acrouzet** [comment]
It behaved like the export (1st frame wave uses previous frame's pitch) in the original GT2.

**Comment by jpage8580** [comment]
Ahh. Apologies. You did say that originally.

Will try to track that down when I get time.
A small sng repro would be useful.

Thanks for this
Jason

**Comment by IFEware** [comment]
https://drive.google.com/file/d/1W9MH7rKWLnId5HPqyTVP_m_stRFVFlY3/view?usp=sharing
Here is a reproduction file
Notice how the pulse width is carried from the previous note but the pitch has been overwritten with the new note
the overwriting of the pitch should come in the second frame wave instead of the first one

**Comment by jpage8580** [comment]
Thanks - and apologies for not looking into this one sooner.
I’m unsure how this can only happen in GTUltra editor vs GTStereo editor
(which is what the code base used initially), as I did t think I’d changed
anything in the playback code that could cause this.

Have you tested in GTStereo too? Will look at this as soon as I can.
Although I’m away until next week

Cheers
Jason

**Comment by jpage8580** [comment]
Hey
I managed to take a quick look at the code. Haven't had the chance to test
with your sng, but I think I found where the pitch was getting set.

Can you test this version?

https://www.dropbox.com/s/fh92oz4ck49mba1/gtultra.exe?dl=0

Cheers
Jason

**Comment by MAHBOD-85** [comment]
This build replicates the original GT2 behaviour

**Comment by IFEware** [comment]
This replicates the original GT2 behavior
There is some problem with sustain F ADSR between the two and how it does not screw up in GT2 when running the file and modifying the ADSR but that is just emulators being more accurate overtime and the export seems to act the exact same way when seeing the sustain F ADSR (to just bug out like a SID chip would)
You can close this issue now
