### ISSUE TITLE
Odd panning upon opening a .sng

### ISSUE THREAD

**Issue by acrouzet** [jpage8580/GTUltra#39]
I recently updated to the latest version of GTUltra, and when opening a .sng I was working on, I noticed all the instruments were panned weirdly, even when switching to mono mode. I've attached the .sng below.

[pointless.zip](https://github.com/jpage8580/GTUltra/files/9651215/pointless.zip)

**Comment by jpage8580** [comment]
Issue caused with instruments that have a high HR/Gate value. 
Have fixed the code. Pushed to V1.3.1 release
