### ISSUE TITLE
Feature request: Ability to select, copy, and paste patterns in the new orderlist view like the old view

### ISSUE THREAD

**Issue by acrouzet** [jpage8580/GTUltra#40]

**Comment by jpage8580** [comment]
Please explain. What can’t you do in the new orderlist view that you could
in the old?

**Comment by acrouzet** [comment]
Pressing shift plus the left and right arrow keys allows you to select patterns in the old order list view. I’m thinking of having the same capability in the new orderlist view with the up and down arrow keys.

**Comment by jpage8580** [comment]
Thanks. Will add this.

**Comment by jpage8580** [comment]
Added in 1.3.2:

> Added Shift+Cursor to select orderlist patterns AND channels in expanded view (UP,DOWN,LEFT & RIGHT)
