### ISSUE TITLE
In the new orderlist: Last row of patterns before FF commands don't play when clicked

### ISSUE THREAD

**Issue by acrouzet** [jpage8580/GTUltra#43]

**Comment by jpage8580** [comment]
Can't repro.
Works fine for me. Is this specific songs?
How are you attempting to play the last row? I just double-click on the
pattern in the expanded order list

**Comment by acrouzet** [comment]
I'm trying to double-click on the pattern in the expanded orderlist but its doesn't go to that row in the song. Maybe it has to do with you changing the patterns in that row while it's still selected in the orderlist?
