### ISSUE TITLE
New Orderlist: Transpose commands are sometimes misinterpreted as repeat commands when switching back to the old orderlist

### ISSUE THREAD

**Issue by acrouzet** [jpage8580/GTUltra#44]

**Comment by jpage8580** [comment]
Possible to send me a screenshot of the new orderlist view with the
transpose values?

**Comment by jpage8580** [comment]
No need for screenshot. Negative transpose values are the issue. Looking
into it now

**Comment by jpage8580** [comment]
Fixed in the latest 1.3.7
