### ISSUE TITLE
Corrupted .sids when exporting songs to some start addresses 

### ISSUE THREAD

**Issue by acrouzet** [jpage8580/GTUltra#51]
Exporting this .sng to .sid with a start address of $9000 results in corrupted playback starting at around 1:07. This is most likely a problem with the player itself since relocating a .sid exported to $1000 to $9000 with sidreloc results in the same corruption.
[Raistlin_50.zip](https://github.com/jpage8580/GTUltra/files/10150795/Raistlin_50.zip)

**Comment by jpage8580** [comment]
Sounds like a bank switching issue. I can’t imagine that there’s a problem
with the code generation specifically at that address.

A quick Google search found this interesting post. See the response re:
data at A000-BFFF

https://www.lemon64.com/forum/viewtopic.php?t=49153

Will look into this.

**Comment by acrouzet** [comment]
Perhaps modify the .sng to work in GT2 and see if this issue occurs in that program, if you haven't already. If it does, then we know it's definitely a problem with the original packer/relocator.

**Comment by acrouzet** [comment]
Have you let Cadaver know about this issue?

**Comment by jpage8580** [comment]
No. I’ve not tested it. Currently at work.
Might be relatively easy to fix. Will just modify the init routine to call
to a function at the very end of the sid, which just rts. That way, it’s
got valid code at the very end.

Will look later today.

**Comment by acrouzet** [comment]
Maybe only apply the fix if the start address is $9000 to avoid any unintended side-effects.

**Comment by jpage8580** [comment]
Actually, that change made no difference when using SIDPlay. However, in
SIDPlay, if I turn on Transparent ROM in emulation settings, it plays
perfectly.

**Comment by jpage8580** [comment]
Fixed.

Now, if SID base address <$a000, but base address+SID size >=$a000, it sets the SID headers play address to the end of the SID. This then automatically sets the ROM bank register to $36 (as noted here.. See line 410+: https://gist.github.com/cbmeeks/2b107f0a8d36fc461ebb056e94b2f4d6)

The new play address just performs a jump to the start of the .SID (the original play address).
In the case of the sng you supplied here:

$aaa6  jmp $9000
