### ISSUE TITLE
New orderlist: Jumping to a pattern that's not the in first row and uses the same transposition value as the pattern above it will make the packed tune continue to use the transposition value of the pattern jumped from

### ISSUE THREAD

**Issue by acrouzet** [jpage8580/GTUltra#56]
I believe this is an issue with the conversion from the new to old orderlist. When converting from new to old, I believe an extra transpose command is needed before a pattern that's being jumped to.

**Comment by jpage8580** [comment]
Will push a fix eventually - codebase is a bit messy with new fixes /
changes, along with me having no time to really get things back into github.

Here's the line to add to fix though: song.c
(function: generateCompressedSongChannel). Add this before the second
compressChannel call. It will force a transpose to be inserted at the start
of the loop position.


 // JP - Loop transpose fix 15/4/23: Always loop to the correct transpose
value at that loop position
lastTranspose = songOrderTranspose[s][c][loopIndex] + 1; // Just make this
dirty to force the transpose to be stored

compressChannel(s, c, loopIndex, endIndex, &p, &lastTranspose,
validateOnly); // compress from loop position to end
