### ISSUE TITLE
GTU Pattern flagged as too much data despite being under 256 bytes

### ISSUE THREAD

**Issue by CrispulentCrisps** [jpage8580/GTUltra#59]
Hello, I have encountered an issue with GTU version 1.5.1
When making a game OST I had encountered an issue with the patter 5E. 
When loading the file with the specified version it will give an error when exporting saying that "PATTERN 5E IS TOO COMPLEX (OVER 256 BYTES PACKED!)"
The issue is that the pattern itself does not contain 256 bytes worth of data. The contents of such are 
- 4 notes
- 2 note off commands
- 4 instrument pointers
- one 3xx effect command
- pattern length of 16 rows

Below is the file itself. This error only appeared in subtune 02, where the other subtunes pack fine (although I have not had the chance to test the subtunes beyond 02 due to this error)

I am also sure that this error persists into 1.5.1.4, but with a different pattern (pattern 0D) even when unused

Hopefully this issue can be resolved as it would be very beneficial for both my circumstance and the program itself.

[Bejewled3CLone - Copy.zip](https://github.com/jpage8580/GTUltra/files/11709111/Bejewled3CLone.-.Copy.zip)

**Comment by jpage8580** [comment]
Fixed
It meant pattern 0x5c
I now reorder the patterns in the order which they are played back. This
allows for potential streaming of GT pattern data - replacing the played
patterns with new data. However, I didn't change the pattern number which
was displayed on-screen to match

Apologies for the inconvenience
Here's the latest version:
https://github.com/jpage8580/GTUltra/releases/tag/V1.5.4.2

Thanks again for your patience!
Jason

**Comment by CrispulentCrisps** [comment]
Thank you for the speedy reply, but a further issue has been encountered.
When trying to export the file it then crashes the program. The following export settings are set

- Buffered sid writes on
- SFX support off
- Volume change off
- Store author info off
- Use zeropage ghost regs off
- Disable optimisations off
- Zeropage SID playback off
- Start ADDR $0C00
- SID 2 ADDR $D440

The below file is the file I attempted to export, with some small changes that give the same output

[Bejewled3CLone - Copy.zip](https://github.com/jpage8580/GTUltra/files/11709829/Bejewled3CLone.-.Copy.zip)

**Comment by jpage8580** [comment]
Try the version here (I also created a .sid that's in the zip too)

https://www.dropbox.com/scl/fi/j0s7ic1l6s9kyni8kn9xs/FixedGTUltra_1.5.4.3.zip?dl=0&rlkey=nckz8jwvbodcxcni5of1gnjbu

**Comment by CrispulentCrisps** [comment]
Hello
with the version you have sent the error has been fixed
thank you so much for the fix :D
