### ISSUE TITLE
Playback is noisy

### ISSUE THREAD

**Issue by HerrSchatten** [jpage8580/GTUltra#63]
During play-back of a song, I can hear very faint crackling noises that randomly pop up. 

They don’t seem to be in any connection to the sounds that are being played, so it’s not an ADSR malfunction. They are audible in the demo songs too, so it’s not my sngs that seem to be the problem. Furthermore, if I play the same files in the "normal" Goattracker, these issues don’t occur at all. 

I guess that there’s something slightly wrong with GT Ultra's sound output, although I have no idea what that could be.

**Comment by jpage8580** [comment]
Hey
Likely due to differences in values stored in the config file - especially
the sample rate.

Take a look at them both in a text editor and check if they match

Cheers
Jason

**Comment by HerrSchatten** [comment]
Thanks for the suggestion. Original Goattracker has the reSID buffer set to 100, GT Ultra has it set to 80, and increasing it got rid of the problem.
