### ISSUE TITLE
Problems exporting to SID

### ISSUE THREAD

**Issue by HerrSchatten** [jpage8580/GTUltra#67]
Maybe I’m just too daft to select the correct options, but when I export a song to SID, I always seem to end up with a file that starts with an audible clicking noise and a split second pause before the actual sound starts. 

I tried various players like SIDplay and Modizer, and it’s the same in all of them. If I use them to pay other SID files, the music starts rightaway. 

Is there maybe some sort of header included that is misinterpreted as sound when playing?

Speaking of Modizer, a GT Ultra made SID file doesn’t seem to include information about the length of the song, which causes Modizer to just play a default length of 2:30, regardless of the actual length. It identifies the length of other SID files just fine and plays them accordingly, though.

The options I use to export are mostly the default ones. 'No' to everything except buffered SID writes, reloc address $1000, zp addresses $fb-$fc.

**Comment by jpage8580** [comment]
If you export using the original GoatTracker editor, do you still notice
these issues?

**Comment by HerrSchatten** [comment]
I experimented a bit, and it seems to be a problem of the players I use to play the files. I got the same results with SID files exported from regular Goattracker. 

Bizarrely , it seems completely random whether SIDplay plays the files correctly or not. The very same files sometimes play perfectly fine, sometimes they don’t.

Still, I don’t know why downloaded SIDs always seem to play fine.

**Comment by jpage8580** [comment]
Can you send me a sng that doesn't play well as SID, and a link to one that
does please?
I'll see if I can work out what's happening

**Comment by HerrSchatten** [comment]
Sure. Here is one of my tracks that shows the aforementioned behaviour when exporting to .sid.
[Destiny.zip](https://github.com/jpage8580/GTUltra/files/12477241/Destiny.zip)
I must admit, though, that at this point I'm not entirely sure I'm not just imagining things.

As far as I can see, none of the example sngs that come with GT Ultra show it, so I guess you can use any of them as a working example.

**Comment by jpage8580** [comment]
Thanks. Will take a look as soon as I can

Cheers
Jason
