### ISSUE TITLE
Ctrl+S saving and pattern splitting don't work

### ISSUE THREAD

**Issue by acrouzet** [jpage8580/GTUltra#7]
When saving with Ctrl+S, GTU says the project was saved, but it isn't.

Pressing Ctrl+K to split a pattern at the cursor position doesn't seem to have an effect anymore.

**Comment by jpage8580** [comment]
Ctrl-S only worked if a song had been previously loaded.
- Have added a check, and now it will open the save dialog box if no song had been previously loaded
- Cleared this flag if Shift-ESC had been used to clear the song.
(still to upload these changes here)

**Comment by jpage8580** [comment]
Pattern splitting worked ok here. However, the orderlist was not processed if an Undo was needed after.
- Have added the checking of orderlist data when editing pattern data too.
- Will need a repro to test if there's still further issues 
(still to upload these changes here)

**Comment by acrouzet** [comment]
> Ctrl-S only worked if a song had been previously loaded.

That's odd, as the reason why I noticed Ctrl+S saving didn't work was because I opened a project, and it was at the state it was when I first saved it with f11.

**Comment by jpage8580** [comment]
Will try to repro this problem again, but I’m really unsure how that can
happen!

**Comment by jpage8580** [comment]
Ctrl-K appears to work OK for me - unless there's no spare patterns - which is what was happening with the first test I was running. Closing this for now, as both ctrl-k and ctrl-s work. Again, if this persists, I'll need clearer repro steps.
