### ISSUE TITLE
KeyOn, KeyOff not working as expected

### ISSUE THREAD

**Issue by SvenSchneiderDVAG** [jpage8580/GTUltra#70]
Hi, I don't know if it's a bug or not correctly documented in F12-help screen.

It says RET = Keyoff and SHIFT + RET = Keyon.

However, no matter waht I'm pressing I only get the "|" char when pressing keyon/keyoff.  I was used to "+++" and "---".
Is it a bug or am I doing it wrong?

Edit: Nevermind! found this in PDF-Documentation
`Enable / Disable using Shift (or CTRL) F12`

I'm closing this now ;)

**Comment by SvenSchneiderDVAG** [comment]
this wierd ... it now works I can see "---" and "+++". I've read the PDF and found information about Shift+Y Key (Auto-Portamento) ... After pressing this key out of curiousity finally keyon / keyoff works as described in help screen. No more "|" when i hit return key. So it works now, but I don't know what fixed it.

**Comment by jpage8580** [comment]
Seems to me that you were in the SIDTracker64 mode - where | displayed to
show the length of the keyon. Possibly got this if you loaded the R-Type
2SID sng, as I wrote that in this mode
